# 2023년

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] =False

### 여기에 해당 연월 사건수 출력(데이터프레임)을 넣어주세요

In [ ]:
#case_2023 로 결과값 도출 요망

### 2023의 경우 메서드가 기존것과 차이가 있으니 참고

In [3]:
# CSV 파일 읽기
population_report = pd.read_csv('./미니프로젝트/2023인구통계.csv', encoding='EUC-KR')

# 빈 딕셔너리 생성
population_result_2023 = {'행정구역': [], '인구수': []}

# 데이터 추출
for i in range(1, len(population_report)):  # len(report) -> len(report_2021)
    population_result_2023['행정구역'].append(population_report['행정구역'][i])
    population_result_2023['인구수'].append(population_report['2023년12월_총인구수'][i])

# DataFrame 생성
population_2023 = pd.DataFrame(population_result_2023)

# 결측치 및 문자열 처리
population_2023['행정구역'] = population_2023['행정구역'].fillna('').str.replace(r'\s*\(.*?\)', '', regex=True)

# '행정구역' 컬럼에서 값이 '강원도'인 행을 제외
population_2023 = population_2023[population_2023['행정구역'] != '강원도']

# 인덱스 재정렬 (선택 사항)
population_2023 = population_2023.reset_index(drop=True)

# '행정구역' 값이 '강원특별자치도'인 행을 '강원도'로 변경
population_2023.loc[population_2023['행정구역'] == '강원특별자치도', '행정구역'] = '강원도'

# 결과 출력
population_2023

       행정구역         인구수
0     서울특별시   9,386,034
1     부산광역시   3,293,362
2     대구광역시   2,374,960
3     인천광역시   2,997,410
4     광주광역시   1,419,237
5     대전광역시   1,442,216
6     울산광역시   1,103,661
7   세종특별자치시     386,525
8       경기도  13,630,821
9       강원도   1,527,807
10     충청북도   1,593,469
11     충청남도   2,130,119
12     전라북도   1,754,757
13     전라남도   1,804,217
14     경상북도   2,554,324
15     경상남도   3,251,158
16  제주특별자치도     675,252

In [ ]:
# 두 데이터프레임을 '행정구역'을 기준으로 병합
merged_df = pd.merge(case_2023, population_2023, on='행정구역', how='inner', suffixes=('_사건수', '_인구수'))

# 결과 출력
merged_df